spring:
  application:
    name: claims-service
  datasource:
    url: jdbc:postgresql://localhost:5432/claims_service
    driver-class-name: org.postgresql.Driver
    username: insurance
    password: insurance123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
          fetch_size: 50
    show-sql: false
    open-in-view: false

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
